// 200+ SaaS tool catalog with pre-filled category and avg monthly cost
export const TOOL_CATALOG = [
  // Communication
  { name: "Slack", category: "Communication", avg_monthly_cost: 87 },
  { name: "Microsoft Teams", category: "Communication", avg_monthly_cost: 60 },
  { name: "Zoom", category: "Communication", avg_monthly_cost: 150 },
  { name: "Google Meet", category: "Communication", avg_monthly_cost: 0 },
  { name: "Loom", category: "Communication", avg_monthly_cost: 80 },
  { name: "Discord", category: "Communication", avg_monthly_cost: 0 },
  { name: "Webex", category: "Communication", avg_monthly_cost: 130 },
  { name: "RingCentral", category: "Communication", avg_monthly_cost: 200 },
  { name: "Dialpad", category: "Communication", avg_monthly_cost: 150 },
  { name: "Intercom", category: "Communication", avg_monthly_cost: 400 },
  { name: "Front", category: "Communication", avg_monthly_cost: 190 },

  // Project Management
  { name: "Asana", category: "Project Management", avg_monthly_cost: 120 },
  { name: "Jira", category: "Project Management", avg_monthly_cost: 140 },
  { name: "Monday.com", category: "Project Management", avg_monthly_cost: 160 },
  { name: "Trello", category: "Project Management", avg_monthly_cost: 50 },
  { name: "ClickUp", category: "Project Management", avg_monthly_cost: 90 },
  { name: "Linear", category: "Project Management", avg_monthly_cost: 80 },
  { name: "Basecamp", category: "Project Management", avg_monthly_cost: 99 },
  { name: "Wrike", category: "Project Management", avg_monthly_cost: 200 },
  { name: "Smartsheet", category: "Project Management", avg_monthly_cost: 250 },
  { name: "Notion", category: "Project Management", avg_monthly_cost: 96 },
  { name: "Coda", category: "Project Management", avg_monthly_cost: 80 },
  { name: "Airtable", category: "Project Management", avg_monthly_cost: 120 },
  { name: "Height", category: "Project Management", avg_monthly_cost: 60 },
  { name: "Shortcut", category: "Project Management", avg_monthly_cost: 70 },
  { name: "Plane", category: "Project Management", avg_monthly_cost: 30 },

  // CRM & Sales
  { name: "Salesforce", category: "CRM & Sales", avg_monthly_cost: 750 },
  { name: "HubSpot", category: "CRM & Sales", avg_monthly_cost: 450 },
  { name: "Pipedrive", category: "CRM & Sales", avg_monthly_cost: 150 },
  { name: "Zoho CRM", category: "CRM & Sales", avg_monthly_cost: 120 },
  { name: "Close", category: "CRM & Sales", avg_monthly_cost: 300 },
  { name: "Freshsales", category: "CRM & Sales", avg_monthly_cost: 100 },
  { name: "Copper", category: "CRM & Sales", avg_monthly_cost: 120 },
  { name: "Apollo.io", category: "CRM & Sales", avg_monthly_cost: 100 },
  { name: "Outreach", category: "CRM & Sales", avg_monthly_cost: 600 },
  { name: "Salesloft", category: "CRM & Sales", avg_monthly_cost: 500 },
  { name: "Gong", category: "CRM & Sales", avg_monthly_cost: 1200 },
  { name: "Chorus", category: "CRM & Sales", avg_monthly_cost: 800 },
  { name: "ZoomInfo", category: "CRM & Sales", avg_monthly_cost: 1500 },
  { name: "Clearbit", category: "CRM & Sales", avg_monthly_cost: 500 },
  { name: "Drift", category: "CRM & Sales", avg_monthly_cost: 400 },

  // Productivity & Docs
  { name: "Google Workspace", category: "Productivity & Docs", avg_monthly_cost: 120 },
  { name: "Microsoft 365", category: "Productivity & Docs", avg_monthly_cost: 150 },
  { name: "Confluence", category: "Productivity & Docs", avg_monthly_cost: 100 },
  { name: "Dropbox Paper", category: "Productivity & Docs", avg_monthly_cost: 50 },
  { name: "Quip", category: "Productivity & Docs", avg_monthly_cost: 80 },
  { name: "Slite", category: "Productivity & Docs", avg_monthly_cost: 60 },
  { name: "GitBook", category: "Productivity & Docs", avg_monthly_cost: 80 },
  { name: "Tettra", category: "Productivity & Docs", avg_monthly_cost: 70 },
  { name: "Guru", category: "Productivity & Docs", avg_monthly_cost: 100 },

  // Design
  { name: "Figma", category: "Design", avg_monthly_cost: 150 },
  { name: "Adobe Creative Cloud", category: "Design", avg_monthly_cost: 600 },
  { name: "Sketch", category: "Design", avg_monthly_cost: 90 },
  { name: "Canva", category: "Design", avg_monthly_cost: 60 },
  { name: "InVision", category: "Design", avg_monthly_cost: 100 },
  { name: "Zeplin", category: "Design", avg_monthly_cost: 80 },
  { name: "Abstract", category: "Design", avg_monthly_cost: 90 },
  { name: "Framer", category: "Design", avg_monthly_cost: 80 },
  { name: "Maze", category: "Design", avg_monthly_cost: 150 },
  { name: "Hotjar", category: "Design", avg_monthly_cost: 80 },
  { name: "Miro", category: "Design", avg_monthly_cost: 100 },
  { name: "Whimsical", category: "Design", avg_monthly_cost: 50 },
  { name: "Lucidchart", category: "Design", avg_monthly_cost: 90 },

  // Dev Tools
  { name: "GitHub", category: "Dev Tools", avg_monthly_cost: 120 },
  { name: "GitLab", category: "Dev Tools", avg_monthly_cost: 200 },
  { name: "Bitbucket", category: "Dev Tools", avg_monthly_cost: 80 },
  { name: "CircleCI", category: "Dev Tools", avg_monthly_cost: 200 },
  { name: "Jenkins", category: "Dev Tools", avg_monthly_cost: 0 },
  { name: "Datadog", category: "Dev Tools", avg_monthly_cost: 500 },
  { name: "New Relic", category: "Dev Tools", avg_monthly_cost: 300 },
  { name: "Sentry", category: "Dev Tools", avg_monthly_cost: 100 },
  { name: "PagerDuty", category: "Dev Tools", avg_monthly_cost: 250 },
  { name: "Postman", category: "Dev Tools", avg_monthly_cost: 60 },
  { name: "Vercel", category: "Dev Tools", avg_monthly_cost: 80 },
  { name: "Netlify", category: "Dev Tools", avg_monthly_cost: 50 },
  { name: "Heroku", category: "Dev Tools", avg_monthly_cost: 200 },
  { name: "Docker", category: "Dev Tools", avg_monthly_cost: 50 },
  { name: "Terraform", category: "Dev Tools", avg_monthly_cost: 0 },
  { name: "Snyk", category: "Dev Tools", avg_monthly_cost: 150 },
  { name: "LaunchDarkly", category: "Dev Tools", avg_monthly_cost: 300 },
  { name: "Split.io", category: "Dev Tools", avg_monthly_cost: 200 },
  { name: "Retool", category: "Dev Tools", avg_monthly_cost: 300 },
  { name: "Supabase", category: "Dev Tools", avg_monthly_cost: 50 },
  { name: "Firebase", category: "Dev Tools", avg_monthly_cost: 100 },
  { name: "Amplitude", category: "Dev Tools", avg_monthly_cost: 400 },
  { name: "Mixpanel", category: "Dev Tools", avg_monthly_cost: 300 },

  // Cloud & Infrastructure
  { name: "AWS", category: "Cloud & Infrastructure", avg_monthly_cost: 2000 },
  { name: "Google Cloud", category: "Cloud & Infrastructure", avg_monthly_cost: 1500 },
  { name: "Microsoft Azure", category: "Cloud & Infrastructure", avg_monthly_cost: 1500 },
  { name: "Cloudflare", category: "Cloud & Infrastructure", avg_monthly_cost: 200 },
  { name: "Fastly", category: "Cloud & Infrastructure", avg_monthly_cost: 400 },
  { name: "DigitalOcean", category: "Cloud & Infrastructure", avg_monthly_cost: 200 },
  { name: "Linode", category: "Cloud & Infrastructure", avg_monthly_cost: 100 },

  // Storage & File Management
  { name: "Dropbox", category: "Storage", avg_monthly_cost: 80 },
  { name: "Box", category: "Storage", avg_monthly_cost: 150 },
  { name: "Google Drive", category: "Storage", avg_monthly_cost: 0 },
  { name: "OneDrive", category: "Storage", avg_monthly_cost: 0 },
  { name: "SharePoint", category: "Storage", avg_monthly_cost: 0 },

  // Marketing
  { name: "Mailchimp", category: "Marketing", avg_monthly_cost: 100 },
  { name: "Klaviyo", category: "Marketing", avg_monthly_cost: 200 },
  { name: "ActiveCampaign", category: "Marketing", avg_monthly_cost: 150 },
  { name: "Marketo", category: "Marketing", avg_monthly_cost: 1500 },
  { name: "Pardot", category: "Marketing", avg_monthly_cost: 1250 },
  { name: "Brevo", category: "Marketing", avg_monthly_cost: 80 },
  { name: "Constant Contact", category: "Marketing", avg_monthly_cost: 75 },
  { name: "ConvertKit", category: "Marketing", avg_monthly_cost: 90 },
  { name: "Drip", category: "Marketing", avg_monthly_cost: 100 },
  { name: "Customer.io", category: "Marketing", avg_monthly_cost: 300 },
  { name: "Iterable", category: "Marketing", avg_monthly_cost: 500 },
  { name: "Braze", category: "Marketing", avg_monthly_cost: 2000 },
  { name: "Semrush", category: "Marketing", avg_monthly_cost: 200 },
  { name: "Ahrefs", category: "Marketing", avg_monthly_cost: 180 },
  { name: "Moz", category: "Marketing", avg_monthly_cost: 150 },
  { name: "Sprout Social", category: "Marketing", avg_monthly_cost: 300 },
  { name: "Hootsuite", category: "Marketing", avg_monthly_cost: 200 },
  { name: "Buffer", category: "Marketing", avg_monthly_cost: 80 },
  { name: "Later", category: "Marketing", avg_monthly_cost: 60 },
  { name: "Google Ads", category: "Marketing", avg_monthly_cost: 0 },
  { name: "Unbounce", category: "Marketing", avg_monthly_cost: 150 },
  { name: "Typeform", category: "Marketing", avg_monthly_cost: 80 },
  { name: "SurveyMonkey", category: "Marketing", avg_monthly_cost: 90 },
  { name: "Optimizely", category: "Marketing", avg_monthly_cost: 500 },
  { name: "VWO", category: "Marketing", avg_monthly_cost: 400 },

  // Analytics & BI
  { name: "Google Analytics", category: "Analytics & BI", avg_monthly_cost: 0 },
  { name: "Tableau", category: "Analytics & BI", avg_monthly_cost: 700 },
  { name: "Looker", category: "Analytics & BI", avg_monthly_cost: 1200 },
  { name: "Power BI", category: "Analytics & BI", avg_monthly_cost: 120 },
  { name: "Domo", category: "Analytics & BI", avg_monthly_cost: 800 },
  { name: "Metabase", category: "Analytics & BI", avg_monthly_cost: 80 },
  { name: "Mode", category: "Analytics & BI", avg_monthly_cost: 300 },
  { name: "Heap", category: "Analytics & BI", avg_monthly_cost: 500 },
  { name: "FullStory", category: "Analytics & BI", avg_monthly_cost: 400 },
  { name: "Segment", category: "Analytics & BI", avg_monthly_cost: 600 },
  { name: "Rudderstack", category: "Analytics & BI", avg_monthly_cost: 200 },

  // Customer Support
  { name: "Zendesk", category: "Customer Support", avg_monthly_cost: 400 },
  { name: "Freshdesk", category: "Customer Support", avg_monthly_cost: 200 },
  { name: "Help Scout", category: "Customer Support", avg_monthly_cost: 150 },
  { name: "Groove", category: "Customer Support", avg_monthly_cost: 100 },
  { name: "LiveChat", category: "Customer Support", avg_monthly_cost: 80 },
  { name: "Tidio", category: "Customer Support", avg_monthly_cost: 60 },
  { name: "Crisp", category: "Customer Support", avg_monthly_cost: 50 },
  { name: "Kustomer", category: "Customer Support", avg_monthly_cost: 600 },
  { name: "Gladly", category: "Customer Support", avg_monthly_cost: 500 },

  // HR & People
  { name: "BambooHR", category: "HR", avg_monthly_cost: 300 },
  { name: "Workday", category: "HR", avg_monthly_cost: 2000 },
  { name: "Gusto", category: "HR", avg_monthly_cost: 250 },
  { name: "Rippling", category: "HR", avg_monthly_cost: 350 },
  { name: "Lattice", category: "HR", avg_monthly_cost: 200 },
  { name: "Culture Amp", category: "HR", avg_monthly_cost: 250 },
  { name: "15Five", category: "HR", avg_monthly_cost: 150 },
  { name: "Lever", category: "HR", avg_monthly_cost: 400 },
  { name: "Greenhouse", category: "HR", avg_monthly_cost: 500 },
  { name: "Workable", category: "HR", avg_monthly_cost: 300 },
  { name: "Jobvite", category: "HR", avg_monthly_cost: 400 },
  { name: "Calendly", category: "HR", avg_monthly_cost: 60 },
  { name: "Officevibe", category: "HR", avg_monthly_cost: 120 },

  // Finance & Accounting
  { name: "QuickBooks", category: "Finance & Accounting", avg_monthly_cost: 80 },
  { name: "Xero", category: "Finance & Accounting", avg_monthly_cost: 70 },
  { name: "FreshBooks", category: "Finance & Accounting", avg_monthly_cost: 55 },
  { name: "Wave", category: "Finance & Accounting", avg_monthly_cost: 0 },
  { name: "Stripe", category: "Finance & Accounting", avg_monthly_cost: 0 },
  { name: "Brex", category: "Finance & Accounting", avg_monthly_cost: 0 },
  { name: "Ramp", category: "Finance & Accounting", avg_monthly_cost: 0 },
  { name: "Expensify", category: "Finance & Accounting", avg_monthly_cost: 100 },
  { name: "Bill.com", category: "Finance & Accounting", avg_monthly_cost: 150 },
  { name: "Sage", category: "Finance & Accounting", avg_monthly_cost: 200 },
  { name: "NetSuite", category: "Finance & Accounting", avg_monthly_cost: 2000 },
  { name: "Recurly", category: "Finance & Accounting", avg_monthly_cost: 200 },
  { name: "Chargebee", category: "Finance & Accounting", avg_monthly_cost: 300 },

  // Identity & Security
  { name: "Okta", category: "Identity & Security", avg_monthly_cost: 400 },
  { name: "Auth0", category: "Identity & Security", avg_monthly_cost: 200 },
  { name: "OneLogin", category: "Identity & Security", avg_monthly_cost: 300 },
  { name: "JumpCloud", category: "Identity & Security", avg_monthly_cost: 200 },
  { name: "1Password", category: "Identity & Security", avg_monthly_cost: 80 },
  { name: "LastPass", category: "Identity & Security", avg_monthly_cost: 80 },
  { name: "Dashlane", category: "Identity & Security", avg_monthly_cost: 70 },
  { name: "Vanta", category: "Identity & Security", avg_monthly_cost: 1000 },
  { name: "Drata", category: "Identity & Security", avg_monthly_cost: 1000 },
  { name: "Crowdstrike", category: "Identity & Security", avg_monthly_cost: 500 },
  { name: "Sophos", category: "Identity & Security", avg_monthly_cost: 300 },

  // E-commerce & Payments
  { name: "Shopify", category: "E-commerce", avg_monthly_cost: 300 },
  { name: "WooCommerce", category: "E-commerce", avg_monthly_cost: 50 },
  { name: "BigCommerce", category: "E-commerce", avg_monthly_cost: 300 },
  { name: "Magento", category: "E-commerce", avg_monthly_cost: 500 },
  { name: "Gorgias", category: "E-commerce", avg_monthly_cost: 200 },
  { name: "Recharge", category: "E-commerce", avg_monthly_cost: 100 },
  { name: "Yotpo", category: "E-commerce", avg_monthly_cost: 200 },

  // Video & Content
  { name: "YouTube", category: "Content", avg_monthly_cost: 0 },
  { name: "Wistia", category: "Content", avg_monthly_cost: 150 },
  { name: "Vimeo", category: "Content", avg_monthly_cost: 50 },
  { name: "Vidyard", category: "Content", avg_monthly_cost: 300 },
  { name: "Descript", category: "Content", avg_monthly_cost: 60 },
  { name: "Riverside.fm", category: "Content", avg_monthly_cost: 80 },
  { name: "Contentful", category: "Content", avg_monthly_cost: 400 },
  { name: "WordPress", category: "Content", avg_monthly_cost: 50 },
  { name: "Webflow", category: "Content", avg_monthly_cost: 150 },
  { name: "HubSpot CMS", category: "Content", avg_monthly_cost: 400 },

  // Automation & Integration
  { name: "Zapier", category: "Automation", avg_monthly_cost: 150 },
  { name: "Make", category: "Automation", avg_monthly_cost: 100 },
  { name: "n8n", category: "Automation", avg_monthly_cost: 50 },
  { name: "Workato", category: "Automation", avg_monthly_cost: 1000 },
  { name: "Boomi", category: "Automation", avg_monthly_cost: 800 },
  { name: "Tray.io", category: "Automation", avg_monthly_cost: 600 },
  { name: "Celigo", category: "Automation", avg_monthly_cost: 500 },
  { name: "MuleSoft", category: "Automation", avg_monthly_cost: 2000 },

  // Learning & Training
  { name: "Udemy for Business", category: "Learning", avg_monthly_cost: 300 },
  { name: "Coursera for Teams", category: "Learning", avg_monthly_cost: 400 },
  { name: "LinkedIn Learning", category: "Learning", avg_monthly_cost: 350 },
  { name: "Pluralsight", category: "Learning", avg_monthly_cost: 200 },
  { name: "Notion Academy", category: "Learning", avg_monthly_cost: 0 },

  // Customer Success
  { name: "Gainsight", category: "Customer Success", avg_monthly_cost: 2000 },
  { name: "ChurnZero", category: "Customer Success", avg_monthly_cost: 1500 },
  { name: "Totango", category: "Customer Success", avg_monthly_cost: 1000 },
  { name: "Catalyst", category: "Customer Success", avg_monthly_cost: 800 },
  { name: "Vitally", category: "Customer Success", avg_monthly_cost: 700 },
  { name: "Planhat", category: "Customer Success", avg_monthly_cost: 600 },
  { name: "Pendo", category: "Customer Success", avg_monthly_cost: 700 },
  { name: "WalkMe", category: "Customer Success", avg_monthly_cost: 900 },
];

export function searchTools(query) {
  if (!query || query.length < 1) return [];
  const q = query.toLowerCase();
  return TOOL_CATALOG.filter((t) => t.name.toLowerCase().includes(q)).slice(0, 8);
}

export function getToolByName(name) {
  return TOOL_CATALOG.find((t) => t.name.toLowerCase() === name.toLowerCase());
}