import { resolveCanonicalApp } from './canonicalApps.ts';

const DAY_MS = 86400000;
export const normalizeGovernanceName = (value = '') => String(value).toLowerCase().trim().replace(/[^a-z0-9]+/g, ' ').trim();
export const isDateOnly = (value) => /^\d{4}-\d{2}-\d{2}$/.test(String(value || '')) && !Number.isNaN(Date.parse(`${value}T00:00:00Z`));
export const dateOnlyUtc = (value) => isDateOnly(value) ? new Date(`${value}T00:00:00Z`) : null;
export const daysBetweenDateOnly = (from, to) => { const a = dateOnlyUtc(from), b = dateOnlyUtc(to); return a && b ? Math.ceil((b.getTime() - a.getTime()) / DAY_MS) : null; };
export const todayDateOnly = (now = new Date()) => now.toISOString().slice(0, 10);
export const subtractNoticeDays = (renewalDate, noticeDays) => { const date = dateOnlyUtc(renewalDate); const days = Number(noticeDays); if (!date || !Number.isInteger(days) || days < 0) return null; date.setUTCDate(date.getUTCDate() - days); return date.toISOString().slice(0, 10); };
export const autoRenewalStatus = (record = {}) => ['yes', 'no', 'unknown'].includes(record.auto_renewal_status) ? record.auto_renewal_status : record.auto_renews === true ? 'yes' : record.auto_renews === false ? 'no' : 'unknown';
export const isVerifiedRenewal = (record = {}) => record.needs_confirmation !== true && ['verified', 'customer_confirmed'].includes(record.verification_status) && isDateOnly(record.renewal_date);
export const contractFingerprint = (record = {}) => [record.company_id || record.created_by_id || '', resolveCanonicalApp(record.canonical_app_id || record.vendor_name || '').canonical_app_id, normalizeGovernanceName(record.contract_name || ''), record.renewal_date || 'unknown', record.billing_frequency || 'unknown'].join('|');
export function deduplicateContracts(records = []) { const priority = { verified: 4, customer_confirmed: 3, needs_review: 2, detected: 1, unknown: 0 }; const chosen = new Map(); for (const record of records) { const key = record.source_fingerprint || contractFingerprint(record); const current = chosen.get(key); if (!current || (priority[record.verification_status] || 0) > (priority[current.verification_status] || 0) || ((priority[record.verification_status] || 0) === (priority[current.verification_status] || 0) && String(record.updated_date || '') > String(current.updated_date || ''))) chosen.set(key, record); } return [...chosen.values()]; }
export function renewalConflict(existing, candidate) { if (!existing || !candidate) return null; const sameApp = resolveCanonicalApp(existing.canonical_app_id || existing.vendor_name).canonical_app_id === resolveCanonicalApp(candidate.canonical_app_id || candidate.vendor_name).canonical_app_id; if (!sameApp) return null; const conflicts = []; if (existing.renewal_date && candidate.renewal_date && existing.renewal_date !== candidate.renewal_date) conflicts.push({ field: 'renewal_date', existing: existing.renewal_date, candidate: candidate.renewal_date }); if (autoRenewalStatus(existing) !== 'unknown' && autoRenewalStatus(candidate) !== 'unknown' && autoRenewalStatus(existing) !== autoRenewalStatus(candidate)) conflicts.push({ field: 'auto_renewal_status', existing: autoRenewalStatus(existing), candidate: autoRenewalStatus(candidate) }); return conflicts.length ? conflicts : null; }
export function potentialOverlap(request, integrations = []) { const requested = resolveCanonicalApp(request.tool_name || ''); const exact = integrations.filter((item) => resolveCanonicalApp(item.canonical_app_id || item.tool_name || '').canonical_app_id === requested.canonical_app_id); const category = integrations.filter((item) => !exact.includes(item) && item.category === request.category); return { exact, category, warnings: [...exact.map((item) => `Existing application match: ${item.tool_name}. Confirm whether this is an additional subscription.`), ...category.map((item) => `Potential overlap with ${item.tool_name}: same category only; capabilities require validation.`)] }; }
export function budgetEvaluation(monthlyBudget, unitCost, seats) { const budget = Number(monthlyBudget), cost = Number(unitCost), quantity = Number(seats); if (!Number.isFinite(budget) || budget <= 0) return { status: 'unavailable', monthlyRequestedCost: Number.isFinite(cost) && cost >= 0 && Number.isInteger(quantity) && quantity > 0 ? cost * quantity : null, impactPct: null }; if (!Number.isFinite(cost) || cost < 0 || !Number.isInteger(quantity) || quantity < 1) return { status: 'unavailable', monthlyRequestedCost: null, impactPct: null }; const total = Math.round(cost * quantity * 100) / 100; return { status: 'available', monthlyRequestedCost: total, impactPct: Math.round((total / budget) * 100) }; }
export const validPurchaseTransition = (from, to) => ({ pending: ['approved', 'rejected', 'deferred'], auto_approved: ['approved', 'rejected', 'deferred'], deferred: ['approved', 'rejected'], approved: ['provisioned'], rejected: [], provisioned: [] }[from] || []).includes(to);
export const governanceActor = (type, user) => ({ actor_type: type, actor_name: type === 'USER' ? (user.full_name || user.email) : type, actor_email: type === 'USER' ? user.email : '' });