import { useState } from "react";

const declineReasons = ["Recommendation not relevant", "Current tool is required", "Cost information incorrect", "Usage information incorrect", "Replacement unsuitable", "Business requirement not understood", "Other"];
const deferOptions = [["30_days", "30 days"], ["60_days_before_renewal", "60 days before renewal"], ["next_audit", "Next audit"], ["custom_date", "Custom date"]];

export default function RecommendationDecisionDetails({ decision, onCancel, onSave, disabled }) {
  const options = decision === "declined" ? declineReasons.map((item) => [item, item]) : deferOptions;
  const [selection, setSelection] = useState(options[0][0]); const [customDate, setCustomDate] = useState("");
  const details = decision === "declined" ? { reason: selection } : { deferOption: selection, customDate: selection === "custom_date" ? customDate : null };
  return <div className="mt-3 flex flex-wrap items-end gap-2 rounded-xl bg-muted/50 p-3"><label className="min-w-52 flex-1 text-xs font-semibold">{decision === "declined" ? "Optional reason" : "Defer until"}<select value={selection} onChange={(event) => setSelection(event.target.value)} className="mt-1 h-9 w-full rounded-lg border border-input bg-background px-2 text-sm">{options.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>{decision === "deferred" && selection === "custom_date" && <label className="text-xs font-semibold">Custom date<input value={customDate} onChange={(event) => setCustomDate(event.target.value)} type="date" className="mt-1 block h-9 rounded-lg border border-input bg-background px-2 text-sm" /></label>}<button type="button" onClick={onCancel} className="h-9 rounded-lg px-3 text-xs font-semibold text-muted-foreground">Cancel</button><button type="button" disabled={disabled || (selection === "custom_date" && !customDate)} onClick={() => onSave(details)} className="h-9 rounded-lg bg-primary px-3 text-xs font-semibold text-primary-foreground disabled:opacity-50">Save</button></div>;
}