const EULA_SECTIONS = [
  ["1. Acceptance", "By accessing or using Stack Sixth, you agree to this End-User License Agreement (EULA). If you use the service for an organization, you represent that you have authority to bind that organization. If you do not agree, do not use the service."],
  ["2. License Grant", "Subject to this EULA and any applicable order or subscription terms, Stack Sixth grants you a limited, non-exclusive, non-transferable, non-sublicensable, revocable license to access and use the service for your organization’s internal business purposes."],
  ["3. Accounts", "You must provide accurate account information, safeguard access credentials, and promptly report unauthorized access. You are responsible for activity performed through your account and for ensuring that authorized users comply with this EULA."],
  ["4. Acceptable Use", "You may not copy, sell, rent, sublicense, reverse engineer, disrupt, probe, or misuse the service; bypass security or usage limits; introduce malicious code; infringe another party’s rights; access the service unlawfully; or use it to build or benchmark a competing product except where applicable law expressly permits."],
  ["5. Customer Data", "You retain ownership of data you submit or connect to Stack Sixth. You grant Stack Sixth a limited right to host, process, transmit, and display that data solely to provide, secure, support, and improve the service. You represent that you have all rights and permissions required to provide the data."],
  ["6. Integrations", "Third-party services and connectors are governed by their own terms and privacy practices. You authorize Stack Sixth to exchange the minimum data needed to provide requested integration features. Stack Sixth is not responsible for third-party services, outages, changes, or data handling."],
  ["7. Recommendations", "Savings estimates, usage insights, renewal alerts, and AI-assisted recommendations are informational and may be incomplete. You remain responsible for procurement, financial, employment, security, and legal decisions and should independently verify material information before acting."],
  ["8. Ownership and Feedback", "Stack Sixth and its licensors retain all rights in the service, software, designs, documentation, trademarks, and related intellectual property. If you provide feedback, you grant Stack Sixth a perpetual, worldwide, royalty-free right to use it without restriction or obligation."],
  ["9. Fees and Subscription", "Paid access is governed by the pricing, billing cycle, renewal, cancellation, and refund terms presented when you subscribe or in an applicable order. Fees are exclusive of taxes unless stated otherwise. Failure to pay may result in suspension or termination."],
  ["10. Availability and Changes", "The service may be updated, modified, suspended, or discontinued. Stack Sixth does not guarantee uninterrupted or error-free availability and may perform maintenance or impose reasonable limits to protect the service and its users."],
  ["11. Confidentiality", "Each party will protect non-public information disclosed by the other using reasonable care and use it only to perform obligations or exercise rights under this EULA, except where disclosure is required by law or the information is independently developed or publicly available without breach."],
  ["12. Disclaimers", "TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SERVICE IS PROVIDED “AS IS” AND “AS AVAILABLE.” STACK SIXTH DISCLAIMS ALL EXPRESS, IMPLIED, AND STATUTORY WARRANTIES, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, AND ACCURACY OF RESULTS."],
  ["13. Limitation of Liability", "TO THE MAXIMUM EXTENT PERMITTED BY LAW, STACK SIXTH WILL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR LOSS OF PROFITS, REVENUE, DATA, OR GOODWILL. STACK SIXTH’S TOTAL LIABILITY ARISING FROM THE SERVICE WILL NOT EXCEED THE AMOUNT YOU PAID FOR THE SERVICE DURING THE 12 MONTHS BEFORE THE EVENT GIVING RISE TO LIABILITY, OR $100 IF YOU PAID NOTHING."],
  ["14. Indemnification", "You will defend, indemnify, and hold harmless Stack Sixth and its affiliates from third-party claims arising from your Customer Data, unlawful or unauthorized use of the service, or material breach of this EULA, except to the extent caused by Stack Sixth."],
  ["15. Suspension and Termination", "You may stop using the service at any time. Stack Sixth may suspend or terminate access for material breach, security risk, unlawful conduct, nonpayment, or as required by law. Upon termination, the license ends. Provisions that by their nature should survive will survive, including ownership, disclaimers, liability limits, indemnification, and governing law."],
  ["16. Governing Law", "This EULA is governed by the laws of the State of Delaware, USA, without regard to conflict-of-law rules. The state and federal courts located in Delaware will have exclusive jurisdiction, and each party consents to their personal jurisdiction and venue."],
  ["17. General Terms", "You may not assign this EULA without Stack Sixth’s written consent; Stack Sixth may assign it in connection with a merger, reorganization, or sale. If a provision is unenforceable, the remainder stays effective. Failure to enforce a provision is not a waiver. This EULA, the Privacy Agreement, and applicable order terms form the entire agreement regarding the service."],
  ["18. Changes and Contact", "Stack Sixth may update this EULA by posting a revised version and updating the effective date. Material changes will apply prospectively. Continued use after the effective date constitutes acceptance. Questions may be directed to the Stack Sixth team through the support channel available in the service."],
];

export default function EndUserLicenseAgreement() {
  return <section id="eula" className="space-y-4 pt-4 border-t border-border/40">
    <div><h2 className="text-xl font-bold tracking-tight">End-User License Agreement</h2><p className="mt-1 text-xs text-muted-foreground">Effective date: July 21, 2026</p></div>
    <div className="glass-card p-5 rounded-xl space-y-5 text-sm text-muted-foreground leading-relaxed">
      <p>This EULA is a legal agreement between you and Stack Sixth governing your use of the Stack Sixth software and services.</p>
      {EULA_SECTIONS.map(([title, body]) => <div key={title}><h3 className="mb-1 text-sm font-semibold text-foreground">{title}</h3><p>{body}</p></div>)}
    </div>
  </section>;
}