import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { base44 } from "@/api/base44Client";
export default function CampaignsAdmin() {
  const qc = useQueryClient(), [form, setForm] = useState({ partner_id: "", campaign_name: "", benefit_type: "COMPLIMENTARY_PLAN", benefit_duration_months: 6, eligible_plan: "STARTER", starts_at: "", ends_at: "" });
  const { data: partners = [] } = useQuery({ queryKey: ["admin-partners"], queryFn: () => base44.entities.Partner.list("partner_name", 100) });
  const { data: campaigns = [] } = useQuery({ queryKey: ["admin-campaigns"], queryFn: () => base44.entities.PartnerCampaign.list("-created_date", 100) });
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const create = async () => { await base44.entities.PartnerCampaign.create({ ...form, campaign_id: `${form.partner_id}_${Date.now()}`, benefit_value: 0, benefit_duration_months: Number(form.benefit_duration_months), starts_at: form.starts_at ? new Date(form.starts_at).toISOString() : new Date().toISOString(), ends_at: form.ends_at ? new Date(form.ends_at).toISOString() : undefined, status: "ACTIVE" }); setForm({ ...form, campaign_name: "" }); qc.invalidateQueries({ queryKey: ["admin-campaigns"] }); };
  return <div className="space-y-5"><div className="glass-card grid gap-3 p-5 sm:grid-cols-2"><select value={form.partner_id} onChange={(e) => set("partner_id", e.target.value)} className="rounded-xl border bg-background px-3 py-2 text-sm"><option value="">Partner</option>{partners.map((p) => <option key={p.id} value={p.partner_id}>{p.partner_name}</option>)}</select><input value={form.campaign_name} onChange={(e) => set("campaign_name", e.target.value)} placeholder="Campaign name" className="rounded-xl border bg-background px-3 py-2 text-sm" /><select value={form.eligible_plan} onChange={(e) => set("eligible_plan", e.target.value)} className="rounded-xl border bg-background px-3 py-2 text-sm">{["STARTER","GROWTH","SCALE"].map((p) => <option key={p}>{p}</option>)}</select><input type="number" min="1" value={form.benefit_duration_months} onChange={(e) => set("benefit_duration_months", e.target.value)} className="rounded-xl border bg-background px-3 py-2 text-sm" /><input type="date" value={form.starts_at} onChange={(e) => set("starts_at", e.target.value)} className="rounded-xl border bg-background px-3 py-2 text-sm" /><input type="date" value={form.ends_at} onChange={(e) => set("ends_at", e.target.value)} className="rounded-xl border bg-background px-3 py-2 text-sm" /><button disabled={!form.partner_id || !form.campaign_name} onClick={create} className="rounded-xl bg-primary px-4 py-2 text-sm font-bold text-primary-foreground disabled:opacity-40">Create campaign</button></div><div className="grid gap-3 sm:grid-cols-2">{campaigns.map((c) => <div key={c.id} className="glass-card p-4"><p className="font-bold">{c.campaign_name}</p><p className="mt-1 text-xs text-muted-foreground">{c.partner_id} · {c.benefit_duration_months} months of {c.eligible_plan}</p></div>)}</div></div>;
}