import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { base44 } from "@/api/base44Client";
export default function CodesAdmin() {
  const qc = useQueryClient(), [campaignId, setCampaignId] = useState(""), [count, setCount] = useState(100), [prefix, setPrefix] = useState("");
  const { data: campaigns = [] } = useQuery({ queryKey: ["admin-campaigns"], queryFn: () => base44.entities.PartnerCampaign.list("-created_date", 100) });
  const { data: codes = [] } = useQuery({ queryKey: ["admin-codes"], queryFn: () => base44.entities.PromotionalCode.list("-created_date", 1000) });
  const generate = async () => { await base44.functions.invoke("generatePromoCodes", { campaign_id: campaignId, count, prefix }); qc.invalidateQueries({ queryKey: ["admin-codes"] }); };
  const exportCsv = () => { const csv = ["code,partner_id,campaign_id,status,redeemed_by,redeemed_at", ...codes.map((c) => [c.code,c.partner_id,c.campaign_id,c.status,c.redeemed_by || "",c.redeemed_at || ""].join(","))].join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); link.download = "stack-sixth-partner-codes.csv"; link.click(); URL.revokeObjectURL(link.href); };
  return <div className="space-y-5"><div className="glass-card grid gap-3 p-5 sm:grid-cols-[1fr_120px_150px_auto]"><select value={campaignId} onChange={(e) => setCampaignId(e.target.value)} className="rounded-xl border bg-background px-3 py-2 text-sm"><option value="">Select campaign</option>{campaigns.map((c) => <option key={c.id} value={c.campaign_id}>{c.campaign_name}</option>)}</select><input type="number" min="1" max="1000" value={count} onChange={(e) => setCount(Number(e.target.value))} className="rounded-xl border bg-background px-3 py-2 text-sm" /><input value={prefix} onChange={(e) => setPrefix(e.target.value)} placeholder="Code prefix" className="rounded-xl border bg-background px-3 py-2 text-sm" /><button disabled={!campaignId} onClick={generate} className="rounded-xl bg-primary px-4 py-2 text-sm font-bold text-primary-foreground disabled:opacity-40">Generate</button></div><div className="flex items-center justify-between"><p className="text-sm font-bold">{codes.length} codes</p><button onClick={exportCsv} className="rounded-xl border px-3 py-2 text-xs font-bold">Export CSV</button></div><div className="max-h-[520px] overflow-auto rounded-2xl border bg-card"><table className="w-full text-left text-xs"><thead className="sticky top-0 bg-muted"><tr><th className="p-3">Code</th><th>Status</th><th>Campaign</th><th>Action</th></tr></thead><tbody>{codes.map((code) => <tr key={code.id} className="border-t"><td className="p-3 font-mono">{code.code}</td><td>{code.status}</td><td>{code.campaign_id}</td><td><button disabled={code.status !== "ACTIVE"} onClick={async () => { await base44.entities.PromotionalCode.update(code.id, { status: "DISABLED" }); qc.invalidateQueries({ queryKey: ["admin-codes"] }); }} className="text-destructive disabled:opacity-30">Disable</button></td></tr>)}</tbody></table></div></div>;
}