import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { base44 } from "@/api/base44Client";
import PromoCodeGenerator from "@/components/admin/PromoCodeGenerator";
export default function CodesAdmin() {
  const qc = useQueryClient();
  const { data: campaigns = [] } = useQuery({ queryKey: ["admin-campaigns"], queryFn: () => base44.entities.PartnerCampaign.list("-created_date", 100) });
  const { data: codes = [] } = useQuery({ queryKey: ["admin-codes"], queryFn: () => base44.entities.PromotionalCode.list("-created_date", 1000) });
  const exportCsv = () => { const csv = ["code,type,partner_id,campaign_id,status,current_redemptions,maximum_redemptions,redeemed_by,redeemed_at", ...codes.map((c) => [c.code,c.single_use ? "unique" : "reusable",c.partner_id,c.campaign_id,c.status,c.current_redemptions || 0,c.maximum_redemptions || 1,c.redeemed_by || "",c.redeemed_at || ""].join(","))].join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); link.download = "stack-sixth-partner-codes.csv"; link.click(); URL.revokeObjectURL(link.href); };
  return <div className="space-y-5"><PromoCodeGenerator campaigns={campaigns} onGenerated={() => qc.invalidateQueries({ queryKey: ["admin-codes"] })} /><div className="flex items-center justify-between"><p className="text-sm font-bold">{codes.length} codes</p><button onClick={exportCsv} className="rounded-xl border px-3 py-2 text-xs font-bold">Export CSV</button></div><div className="max-h-[520px] overflow-auto rounded-2xl border bg-card"><table className="w-full text-left text-xs"><thead className="sticky top-0 bg-muted"><tr><th className="p-3">Code</th><th>Type</th><th>Usage</th><th>Status</th><th>Campaign</th><th>Action</th></tr></thead><tbody>{codes.map((code) => <tr key={code.id} className="border-t"><td className="p-3 font-mono">{code.code}</td><td>{code.single_use ? "Unique" : "Reusable"}</td><td>{code.current_redemptions || 0}/{code.maximum_redemptions || 1}</td><td>{code.status}</td><td>{code.campaign_id}</td><td><button disabled={code.status !== "ACTIVE"} onClick={async () => { await base44.entities.PromotionalCode.update(code.id, { status: "DISABLED" }); qc.invalidateQueries({ queryKey: ["admin-codes"] }); }} className="text-destructive disabled:opacity-30">Disable</button></td></tr>)}</tbody></table></div></div>;
}