import { useState } from "react";
import { base44 } from "@/api/base44Client";
export default function PlanAdminRow({ plan, onSaved }) {
  const legacy = plan.plan_key === "FREE_LAUNCH";
  const [form, setForm] = useState({ monthly_price: plan.monthly_price ?? "", annual_price: plan.annual_price ?? "", integration_limit: plan.integration_limit, features: (plan.features || []).join("\n"), entitlements: JSON.stringify(plan.entitlements || {}, null, 2), active: legacy ? false : plan.active });
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const save = async () => { let entitlements; try { entitlements = JSON.parse(form.entitlements || "{}"); } catch { alert("Entitlements must be valid JSON."); return; } await base44.entities.PlanDefinition.update(plan.id, { monthly_price: Number(form.monthly_price || 0), annual_price: Number(form.annual_price || 0), integration_limit: Number(form.integration_limit), features: form.features.split("\n").map((item) => item.trim()).filter(Boolean), entitlements, active: legacy ? false : form.active }); onSaved(); };
  const statusLabel = legacy ? "Legacy" : form.active ? "Active" : "Inactive";
  const statusStyle = legacy ? "bg-amber-100 text-amber-800" : form.active ? "bg-emerald-100 text-emerald-700" : "bg-muted";
  return <details className="glass-card p-4"><summary className="flex cursor-pointer items-center justify-between"><div><p className="font-bold">{plan.name}</p><p className="text-xs text-muted-foreground">{plan.plan_key}</p></div><span className={`rounded-lg px-3 py-1 text-xs font-bold ${statusStyle}`}>{statusLabel}</span></summary><div className="mt-4 grid gap-3 sm:grid-cols-3"><label className="text-xs">Monthly<input value={form.monthly_price} onChange={(e) => set("monthly_price", e.target.value)} className="mt-1 w-full rounded-lg border bg-background px-2 py-2" /></label><label className="text-xs">Annual<input value={form.annual_price} onChange={(e) => set("annual_price", e.target.value)} className="mt-1 w-full rounded-lg border bg-background px-2 py-2" /></label><label className="text-xs">Integrations<input value={form.integration_limit} onChange={(e) => set("integration_limit", e.target.value)} className="mt-1 w-full rounded-lg border bg-background px-2 py-2" /></label><label className="text-xs sm:col-span-3">Features<textarea value={form.features} onChange={(e) => set("features", e.target.value)} rows="5" className="mt-1 w-full rounded-lg border bg-background p-2" /></label><label className="text-xs sm:col-span-3">Entitlements JSON<textarea value={form.entitlements} onChange={(e) => set("entitlements", e.target.value)} rows="5" className="mt-1 w-full rounded-lg border bg-background p-2 font-mono" /></label><div className="flex items-center gap-2 sm:col-span-3">{legacy ? <p className="text-xs text-muted-foreground">Existing workspaces keep this plan until their access ends. New workspaces cannot select it.</p> : <button onClick={() => set("active", !form.active)} className="rounded-xl border px-3 py-2 text-xs font-bold">{form.active ? "Deactivate" : "Activate"}</button>}<button onClick={save} className="rounded-xl bg-primary px-4 py-2 text-xs font-bold text-primary-foreground">Save plan</button></div></div></details>;
}