import { createClientFromRequest } from 'npm:@base44/sdk@0.8.44';
import { resolveOrganizationContext } from '../../shared/organizationContext.ts';
import { resolveCanonicalApp } from '../../shared/canonicalApps.ts';
import { deduplicateContracts, renewalConflict, todayDateOnly, daysBetweenDateOnly } from '../../shared/governanceReliability.ts';

export default async function(req) {
  try {
    const base44 = createClientFromRequest(req); const user = await base44.auth.me(); if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 }); const context = await resolveOrganizationContext(base44, user); if (!context) return Response.json({ error: 'Company setup required' }, { status: 400 });
    const body = await req.json().catch(() => ({})); let accessToken; try { ({ accessToken } = await base44.asServiceRole.connectors.getCurrentAppUserConnection('6a2c11c93a60aebc9a354fd8')); } catch (error) { return Response.json({ connected: false, error: error.message }); }
    if (body.checkOnly) return Response.json({ connected: true, candidates: [] });
    const headers = { Authorization: `Bearer ${accessToken}` }; const query = 'newer_than:2y ("renewal date" OR "renews on" OR "next billing date" OR "next payment")'; const listRes = await fetch(`https://gmail.googleapis.com/gmail/v1/users/me/messages?maxResults=80&q=${encodeURIComponent(query)}`, { headers });
    if (!listRes.ok) { const data = await listRes.json().catch(() => ({})); throw new Error(data?.error?.message || (listRes.status === 403 ? 'Gmail read permission is missing. Reconnect Gmail and approve read-only email access.' : `Gmail search failed (${listRes.status})`)); }
    const messages = (await listRes.json()).messages || []; const decode = (value) => { if (!value) return ''; const normalized = value.replace(/-/g,'+').replace(/_/g,'/'); return atob(normalized.padEnd(Math.ceil(normalized.length/4)*4,'=')); }; const extractText = (payload) => { let text = payload?.body?.data ? decode(payload.body.data) : ''; for (const part of payload?.parts || []) text += `\n${extractText(part)}`; return text.replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/\s+/g,' '); };
    const senderVendor = (from) => { const domain = from.match(/@([\w.-]+)/)?.[1]?.toLowerCase(); if (!domain) return null; const root = domain.split('.').slice(-2,-1)[0]; if (!root || ['google','gmail','outlook','stripe','paypal'].includes(root)) return null; return root.charAt(0).toUpperCase()+root.slice(1).replace(/[-_]/g,' '); };
    const parseDate = (text) => { const match = text.match(/(?:renews?|renewal date|next billing date|next payment)[^\n.]{0,55}?((?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)\s+\d{1,2},?\s+\d{4})/i); const date = match ? new Date(match[1]) : null; return date && !Number.isNaN(date.getTime()) ? date.toISOString().slice(0,10) : null; };
    const candidates = []; await Promise.all(messages.slice(0,50).map(async ({id}) => { const response = await fetch(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${id}?format=full`,{headers}); if (!response.ok) return; const message=await response.json(); const map=Object.fromEntries((message.payload?.headers||[]).map((h)=>[h.name.toLowerCase(),h.value])); const subject=map.subject||''; if (/^(fw|fwd):/i.test(subject)) return; const text=`${subject} ${extractText(message.payload||{})}`.slice(0,16000); if (!/(renewal date|renews on|next billing date|next payment)/i.test(text) || (/unsubscribe/i.test(text) && !/(invoice|receipt|payment|account)/i.test(text))) return; const vendor=senderVendor(map.from||''); const renewalDate=parseDate(text); if (!vendor || !renewalDate) return; const days=daysBetweenDateOnly(todayDateOnly(),renewalDate); if (days !== null && days < -30) return; const frequency=/quarterly|every three months/i.test(text)?'quarterly':/annual|annually|yearly|per year/i.test(text)?'annual':/monthly|per month/i.test(text)?'monthly':'unknown'; candidates.push({ vendor_name:vendor, canonical_app_id:resolveCanonicalApp(vendor).canonical_app_id, renewal_date:renewalDate, billing_frequency:frequency, renewal_source:'gmail', source_record_id:id, source_label:'Gmail billing email', source_timestamp:new Date(Number(message.internalDate||Date.now())).toISOString(), subject, verification_status:'detected', needs_confirmation:true, auto_renewal_status:'unknown', renewal_confidence:75 }); }));
    const unique=[...new Map(candidates.map((item)=>[[item.canonical_app_id,item.renewal_date,item.billing_frequency].join('|'),item])).values()]; const ownerId=context.company.owner_user_id||context.company.created_by_id; const [scoped,legacy]=await Promise.all([base44.asServiceRole.entities.Contract.filter({company_id:context.companyId}),base44.asServiceRole.entities.Contract.filter({created_by_id:ownerId})]); const contracts=deduplicateContracts([...scoped,...legacy]); const suggestions=unique.map((item)=>{ const same=contracts.filter((record)=>resolveCanonicalApp(record.canonical_app_id||record.vendor_name).canonical_app_id===item.canonical_app_id); const duplicate=same.some((record)=>record.renewal_date===item.renewal_date); const conflict=same.find((record)=>renewalConflict(record,item)); return {...item,duplicate,conflict:conflict?{contract_id:conflict.id,values:renewalConflict(conflict,item)}:null}; }).filter((item)=>!item.duplicate);
    return Response.json({connected:true,candidates:suggestions,suggestions,scanned:Math.min(messages.length,50),duplicates_suppressed:unique.length-suggestions.length});
  } catch (error) { console.error('Gmail renewal detection failed',error); return Response.json({connected:true,error:error.message},{status:200}); }
}