import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, CircleHelp, LockKeyhole, MailSearch, RefreshCw, ShieldCheck } from "lucide-react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { toast } from "sonner";
import RenewalSuggestion from "@/components/contracts/RenewalSuggestion";

const CONNECTOR_ID = "6a2c11c93a60aebc9a354fd8";
export default function RenewalDetectionPanel({ onConfirmed }) {
  const [connected, setConnected] = useState(null), [scanning, setScanning] = useState(false), [suggestions, setSuggestions] = useState([]), [confirming, setConfirming] = useState("");
  const check = useCallback(async () => { const authed = await base44.auth.isAuthenticated(); if (!authed) return setConnected(false); const response = await base44.functions.invoke("detectRenewalsFromGmail", { checkOnly: true }); setConnected(Boolean(response.data?.connected)); }, []);
  useEffect(() => { check(); }, [check]);
  const connect = async () => { const popup = window.open("", "_blank"); const url = await base44.connectors.connectAppUser(CONNECTOR_ID); if (!popup) return toast.error("Please allow pop-ups to connect Gmail."); popup.location.href = url; const timer = setInterval(() => { if (popup.closed) { clearInterval(timer); check(); } }, 500); };
  const scan = async () => { setScanning(true); const response = await base44.functions.invoke("detectRenewalsFromGmail", {}); setScanning(false); if (response.data?.error) return toast.error(response.data.error); setSuggestions(response.data?.suggestions || []); if (!response.data?.suggestions?.length) toast.info("No clear renewal dates were found."); };
  const confirm = async (item) => { setConfirming(item.vendor_name); const days = Math.ceil((new Date(item.renewal_date) - new Date()) / 86400000); const contract = await base44.entities.Contract.create({ vendor_name: item.vendor_name, last_renewal_date: item.last_renewal_date, renewal_date: item.renewal_date, billing_frequency: item.billing_frequency, renewal_source: "gmail", renewal_confidence: item.renewal_confidence, contract_type: "Other", needs_confirmation: false, decision_state: "undecided", status: days <= 60 ? "Expiring Soon" : "Active" }); const user = await base44.auth.me(); if (user.role === "admin") await base44.entities.AuditTrailEvent.create({ entity_type: "Contract", entity_id: contract.id, entity_label: contract.vendor_name, action: "created", actor_name: user.full_name || user.email, actor_email: user.email, new_value: contract.renewal_date, note: "Renewal detected from Gmail and confirmed." }); setSuggestions((items) => items.filter((suggestion) => suggestion.vendor_name !== item.vendor_name)); setConfirming(""); onConfirmed(); };
  return <section className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-center"><div className="flex min-w-0 flex-1 items-start gap-3"><div className="rounded-xl bg-primary/10 p-2.5"><MailSearch className="h-5 w-5 text-primary" /></div><div><h3 className="text-sm font-bold">Discover renewals automatically</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">Connect Gmail to find renewal dates hiding in invoices and software subscription emails.</p><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-[10px] text-muted-foreground"><span><ShieldCheck className="mr-1 inline h-3 w-3" />Read-only access</span><span><LockKeyhole className="mr-1 inline h-3 w-3" />Messages aren’t stored</span><span><CheckCircle2 className="mr-1 inline h-3 w-3" />Every date requires confirmation</span></div></div></div><div className="flex items-center gap-2"><Popover><PopoverTrigger asChild><button className="flex items-center gap-1 text-xs font-semibold text-muted-foreground hover:text-foreground"><CircleHelp className="h-3.5 w-3.5" />How it works</button></PopoverTrigger><PopoverContent align="end"><ol className="space-y-2 text-xs text-muted-foreground"><li>1. Governance scans relevant emails.</li><li>2. It identifies possible renewal dates.</li><li>3. You review the results.</li><li>4. Nothing is added without confirmation.</li></ol></PopoverContent></Popover><Button size="sm" variant={connected ? "outline" : "default"} onClick={connected ? scan : connect} disabled={scanning || connected === null}><RefreshCw className={`h-3.5 w-3.5 ${scanning ? "animate-spin" : ""}`} />{connected ? (scanning ? "Scanning…" : "Scan Gmail") : "Connect Gmail"}</Button></div></div>{suggestions.length > 0 && <div className="mt-4 space-y-2 border-t pt-4">{suggestions.map((suggestion) => <RenewalSuggestion key={suggestion.vendor_name} suggestion={suggestion} confirming={confirming === suggestion.vendor_name} onConfirm={confirm} />)}</div>}</section>;
}