import { useEffect, useState } from "react";
import { base44 } from "@/api/base44Client";
import PricingHeader from "@/components/pricing/PricingHeader";
import SignupProgress from "@/components/signup/SignupProgress";
import CompanyDetailsForm from "@/components/signup/CompanyDetailsForm";
import AccessSelector from "@/components/signup/AccessSelector";
import { trackAcquisition } from "@/lib/acquisitionEvents";
export default function SignupSetup() {
  const pending = JSON.parse(sessionStorage.getItem("stackSixthSignup") || "{}");
  const choice = JSON.parse(sessionStorage.getItem("stackSixthAccessChoice") || "{}");
  const [step, setStep] = useState(1), [company, setCompany] = useState({ name: pending.company_name || "", company_size: "10-49", industry: "SaaS", estimated_software_apps: "", contact_role: "Founder / CEO", contact_first_name: pending.first_name || "", contact_last_name: pending.last_name || "" });
  const [interval, setInterval] = useState(choice.billing_interval || "monthly"), [selected, setSelected] = useState(choice.plan || "STARTER"), [promo, setPromo] = useState(choice.promo_code || sessionStorage.getItem("stackSixthPromoCode") || ""), [promoState, setPromoState] = useState({ loading: false, error: "", data: null }), [loading, setLoading] = useState(false);
  useEffect(() => { base44.auth.isAuthenticated().then((ok) => { if (!ok) base44.auth.redirectToLogin("/signup/setup"); }); }, []);
  const applyPromo = async (code) => { setPromoState({ loading: true, error: "", data: null }); trackAcquisition("promo_code_entered"); try { const response = await base44.functions.invoke("validatePromoCode", { code }); const plan = response.data.eligible_plan; setPromo(code); setSelected(plan); setPromoState({ loading: true, error: "", data: response.data }); trackAcquisition("promo_code_validated", { partner: response.data.partner_name }); await base44.functions.invoke("initializeAccess", { company, plan, billing_interval: interval, promo_code: code }); sessionStorage.removeItem("stackSixthSignup"); sessionStorage.removeItem("stackSixthAccessChoice"); window.location.href = "/onboarding"; } catch (error) { setPromoState({ loading: false, error: error.response?.data?.error || error.message, data: null }); } };
  const submit = async () => { setLoading(true); try { if (!promo && selected !== "ENTERPRISE" && window.self !== window.top) { alert("Secure checkout is available from the published Stack Sixth app, not inside preview."); return; } const response = await base44.functions.invoke("initializeAccess", { company, plan: selected, billing_interval: interval, promo_code: promo || undefined }); trackAcquisition("plan_selected", { plan: selected, interval }); if (response.data.contact_required || selected === "ENTERPRISE") { await base44.functions.invoke("submitEnterpriseInterest", {}); window.location.href = "/contact-sales"; return; } if (!promo) { trackAcquisition("checkout_started", { plan: selected, interval }); const checkout = await base44.functions.invoke("createSubscriptionCheckout", { plan: selected, billing_interval: interval }); window.location.href = checkout.data.checkout_url || checkout.data.redirect_url; return; } sessionStorage.removeItem("stackSixthSignup"); sessionStorage.removeItem("stackSixthAccessChoice"); window.location.href = "/onboarding"; } catch (error) { setPromoState((current) => ({ ...current, error: error.response?.data?.error || error.message })); } finally { setLoading(false); } };
  return <div className="min-h-screen bg-background"><PricingHeader /><main className="mx-auto max-w-6xl px-4 py-10"><SignupProgress step={step} /><div className="glass-card mx-auto p-6 sm:p-8">{step === 1 ? <CompanyDetailsForm value={company} onChange={setCompany} onNext={() => setStep(2)} /> : <AccessSelector companySize={company.company_size} interval={interval} setInterval={setInterval} selected={selected} setSelected={setSelected} promo={promo} promoState={promoState} onPromo={applyPromo} onSubmit={submit} loading={loading} />}</div></main></div>;
}