import { createClientFromRequest } from 'npm:@base44/sdk@0.8.44';
import { resolveOrganizationContext, companyScope } from '../../shared/organizationContext.ts';
import { budgetEvaluation, governanceActor, potentialOverlap } from '../../shared/governanceReliability.ts';

export default async function(req) {
  try {
    const base44 = createClientFromRequest(req); const user = await base44.auth.me(); if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });
    const body = await req.json(); const { tool_name, category, estimated_monthly_cost, requested_seats, justification, team_affected, use_case, vendor_url } = body;
    if (!tool_name || !category) return Response.json({ error: 'tool_name and category are required' }, { status: 400 });
    const unitCost = estimated_monthly_cost === '' || estimated_monthly_cost == null ? null : Number(estimated_monthly_cost); const seats = Number(requested_seats || 1);
    if ((unitCost !== null && (!Number.isFinite(unitCost) || unitCost < 0)) || !Number.isInteger(seats) || seats < 1) return Response.json({ error: 'Cost and seats must be valid non-negative values' }, { status: 400 });
    const context = await resolveOrganizationContext(base44, user); if (!context) return Response.json({ error: 'Complete company setup before submitting a purchase request' }, { status: 400 });
    const ownerId = context.company.owner_user_id || context.company.created_by_id; const service = base44.asServiceRole.entities;
    const [integrations, policies, rolePolicies] = await Promise.all([service.SaasIntegration.filter({ company_id: context.companyId }), service.PurchasePolicy.filter({ is_active: true, created_by_id: ownerId }), service.RolePolicy.filter({ created_by_id: ownerId })]);
    const overlap = potentialOverlap({ tool_name, category }, integrations); const budget = budgetEvaluation(context.company.monthly_saas_budget, unitCost, seats); const policy = policies[0] || null; const conflictFlags = [];
    if (policy?.blocked_categories?.includes(category)) conflictFlags.push(`Category "${category}" is blocked by policy "${policy.rule_name}".`);
    if (budget.status === 'available' && Number.isFinite(policy?.max_budget_pct_per_request) && budget.impactPct > policy.max_budget_pct_per_request) conflictFlags.push(`Requested cost is ${budget.impactPct}% of the verified monthly budget; policy maximum is ${policy.max_budget_pct_per_request}%.`);
    if (budget.monthlyRequestedCost !== null && Number.isFinite(policy?.requires_manual_above) && budget.monthlyRequestedCost > policy.requires_manual_above) conflictFlags.push(`Requested cost exceeds the configured manual-review threshold of $${policy.requires_manual_above}/month.`);
    if (overlap.exact.length && policy?.block_redundant_tools === true) conflictFlags.push('An exact canonical application match exists; confirm whether this is an additional subscription.');
    if (team_affected && rolePolicies.length) { const role = rolePolicies.find((item) => team_affected.toLowerCase().includes(String(item.role_name || '').toLowerCase())); if (role?.blocked_tools?.some((item) => tool_name.toLowerCase() === String(item).toLowerCase())) conflictFlags.push(`Tool is blocked for role "${role.role_name}" by role policy.`); }
    const explicitlyAutoEligible = policy && budget.monthlyRequestedCost !== null && ((Number.isFinite(policy.max_auto_approve_cost) && budget.monthlyRequestedCost <= policy.max_auto_approve_cost) || policy.auto_approve_categories?.includes(category));
    const recommendation = !conflictFlags.length && explicitlyAutoEligible ? 'approve' : 'needs_review'; const status = recommendation === 'approve' ? 'auto_approved' : 'pending';
    const evidence = { company_id: context.companyId, policy_id: policy?.id || null, policy_name: policy?.rule_name || null, budget_status: budget.status, budget_value: budget.status === 'available' ? Number(context.company.monthly_saas_budget) : null, requested_cost: budget.monthlyRequestedCost, requested_seats: seats, exact_application_matches: overlap.exact.map((item) => item.id), category_candidates: overlap.category.map((item) => item.id), evaluated_at: new Date().toISOString() };
    const reasons = [`Requested ${seats} seat${seats === 1 ? '' : 's'}${budget.monthlyRequestedCost === null ? ' with cost unavailable' : ` at $${budget.monthlyRequestedCost}/month`}.`, budget.status === 'unavailable' ? 'Budget status unavailable because no authoritative customer budget is present.' : `Budget impact is ${budget.impactPct}% of the customer budget.`, policy ? `Evaluated against policy "${policy.rule_name}".` : 'No active purchase policy exists; human review is required.', ...overlap.warnings, ...conflictFlags];
    const request = await service.PurchaseRequest.create({ ...companyScope(context), requester_user_id: user.id, requester_name: user.full_name || '', requester_email: user.email || '', tool_name, category, ...(unitCost === null ? {} : { estimated_monthly_cost: unitCost }), ...(budget.monthlyRequestedCost === null ? {} : { requested_monthly_cost: budget.monthlyRequestedCost }), requested_seats: seats, justification: justification || '', team_affected: team_affected || '', use_case: use_case || '', vendor_url: vendor_url || '', status, execution_state: 'not_started', ai_recommendation: recommendation, decision_reason: reasons.join(' '), evaluation_evidence: evidence, conflict_flags: conflictFlags, redundancy_warnings: overlap.warnings, budget_status: budget.status, ...(budget.impactPct === null ? {} : { budget_impact_pct: budget.impactPct }) });
    await service.AuditTrailEvent.create({ company_id: context.companyId, entity_type: 'PurchaseRequest', entity_id: request.id, entity_label: tool_name, action: 'created', ...governanceActor('SYSTEM', user), new_value: status, note: 'Deterministic policy evaluation completed from recorded evidence.', source: 'purchase_policy' });
    return Response.json({ request, ai_recommendation: recommendation, decision_reason: request.decision_reason, conflict_flags: conflictFlags, redundancy_warnings: overlap.warnings, budget_status: budget.status, budget_impact_pct: budget.impactPct, total_monthly_cost: budget.monthlyRequestedCost });
  } catch (error) { console.error('Purchase evaluation failed', error); return Response.json({ error: error.message }, { status: 500 }); }
}